-- #203: market_sparklines (0035) was the one function without an empty search_path. It is security
-- invoker, so a member could only ever have shadowed a name for their own call, but every other
-- function pins it and now this one does too.
--
-- The audit also asked for anon and authenticated to lose EXECUTE on net.http_get and friends. The
-- pg_net extension is owned by supabase_admin, and a migration runs as postgres, which can neither
-- revoke on those functions nor on the net schema ("no privileges could be revoked"), so that stays
-- as Supabase ships it. Those roles can't reach the net schema through PostgREST, which exposes
-- only public; the door would be a public function that calls net.* and is executable by them, and
-- tests/db/security-integrity.test.ts now checks no such function exists.
alter function public.market_sparklines(uuid[], integer) set search_path = '';
